defaults:
  - algo: xRL_algo
  - task: null
  - logging: default
  - _self_

hydra:
  searchpath:
    - pkg://xRL/cfg

task: null

#Subscribed default config for the env initialization

device: 'cuda'
sim_device: 0
graphics_device_id: 0

rl_buffer_device: 'cuda' #cpu

num_envs : 4096 
seed : 42 
max_time : null 
max_step: null
max_iterations : 30000 

headless: True

with_imitation_amp : True

evaluator : False
eval_headless: True
eval_num_envs: 150

tracking_training : 
  neptune: False
  wandb: False

#For alg info tracking
info_track_keys: null # a list of keys to track in the info dict returned by env.step
info_track_step: null # ['last', 'all-episode', 'all-step'], whether to track the info in the last
                      # step or all steps. for all steps, whether to sum all values in episodes
                      # up or keep track per-step values

#for loading the policy
artifact: null



